[package]
authors = ["github.com/golmman"]
name = "termgol"
version = "1.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.22", features = ["derive"] }
nanorand = "0.7.0"
regex = "1.6.0"
term2d = "0.6.1"
