[data]
tile_ids = """
[#][#][#][#][#][#][#][#][#][#][#][#][#][#][#][#][#][#][#][#][#][#][#][#][#][#][#]
[#][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][#]
[#][:][_][_][_][v][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][#]
[#][:][_][_][v][v][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][#]
[#][:][_][_][v][v][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][#]
[#][:][_][v][_][_][_][_][_][_][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][#]
[#][:][_][_][_][_][:][:][:][_][_][_][:][:][:][:][:][:][:][:][:][:][:][:][:][:][#]
[#][:][:][:][:][:][:][:][:][:][:][_][:][:][:][:][:][:][_][_][_][_][_][:][:][:][#]
[#][:][:][:][:][:][:][:][:][:][:][_][:][:][:][:][:][:][_][_][_][_][_][:][:][:][#]
[#][:][:][:][:][:][:][:][:][:][:][_][:][:][:][:][:][:][_][_][:][_][_][:][:][:][#]
[#][:][:][:][:][:][:][:][:][_][_][_][_][:][:][:][:][:][_][_][_][_][_][:][:][:][#]
[#][:][:][:][:][:][:][:][:][_][_][_][_][:][:][:][:][:][_][_][_][_][_][:][:][:][#]
[#][:][:][:][:][:][:][:][:][_][_][_][_][_][:][:][:][:][_][_][:][_][_][_][:][:][#]
[#][:][:][:][:][:][:][:][:][_][_][_][_][_][:][:][:][:][_][_][:][_][_][_][:][:][#]
[#][:][:][:][:][:][:][:][:][_][_][_][_][_][:][:][:][:][_][_][:][_][_][_][_][:][#]
[#][:][:][:][:][:][:][:][:][_][_][_][_][_][:][:][:][:][:][:][:][_][_][_][_][:][#]
[#][:][:][:][:][:][:][:][:][:][:][v][v][:][:][:][:][:][:][:][:][_][_][:][:][:][#]
[#][:][:][:][:][:][:][:][:][:][:][v][v][:][:][:][:][:][:][:][:][_][_][:][:][:][#]
[#][:][:][:][:][:][:][:][:][:][:][:][v][v][v][v][:][:][:][:][:][_][_][:][:][:][#]
[#][:][:][:][:][:][:][:][:][:][:][:][:][v][v][v][v][:][:][:][:][:][:][:][:][:][#]
[#][:][:][:][:][:][:][:][:][:][:][:][:][v][v][v][:][:][:][:][:][:][:][:][:][:][#]
[#][:][:][:][:][:][:][:][:][:][:][:][:][:][v][:][:][:][:][:][:][:][:][:][:][:][#]
[#][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][:][#]
[#][#][#][#][#][#][#][#][#][#][#][#][#][#][#][#][#][#][#][#][#][#][#][#][#][#][#]
"""
