[follower]
[follower.base]
id = "follower"
bg_color = nan
fg_color = 214
name = "Follower"
npc_class = "debug"
walk_delay = 1 # frames per tile
run_delay = 0
attack_delay = 3
[follower.animation]
idle = [
    [
        ".i.", ".i.", ".i.", ".i.", ".i.", ".i.", ".i.", ".i.",
        ",i,", ",i,", ",ï,", ",ï,", ",ï,", ",ï,", ".ï.", ".ï.",
    ],
]
walk = [[",i.", ",i.", ",i,", ",i,", ".i,", ".i,"]]

[imp]
[imp.base]
id = "imp"
bg_color = nan
fg_color = 183
name = "Imp"
npc_class = "worker"
walk_delay = 2
run_delay = 0
attack_delay = 3
[imp.animation]
idle = [
    [
        ":Ö:", ":Ö:", ":Ö:", ":Ö:", ":Ö:", ":Ö:", ":Ö:", ":Ö:",
        ":Ö:", ":Ö:", ";Ô;", ";Ô;", ";Ô;", ";Ô;", ":Ö:", ":Ö:",
    ],
]
walk = [[";Ö:", ";Ö:", ";Ö;", ";Ö;", ":Ö;", ":Ö;"]]
